wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.10
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.9
    start_time: 1731745010
    t:
      1:
      - 1
      - 5
      2:
      - 1
      - 5
      3:
      - 16
      4: 3.6.9
      5: 0.12.10
      8:
      - 5
architecture:
  desc: null
  value: CNN
dataset:
  desc: null
  value: CIFAR-100
epochs:
  desc: null
  value: 10
learning_rate:
  desc: null
  value: 0.02
